### ISSUE TITLE
line-endings of generated files neither DOS nor UNIX (MAC instead)

### ISSUE THREAD

**Issue by cgcostume** [cginternals/khrbinding-generator#14]
Generated files have all wrong file endings. Various compilers will compile with warnings or not at all: msvc15 `warning C4335: Mac file format detected: please convert the source file to either DOS or UNIX format` - further more the files are not displayed correctly in sublime and other common editors (additional empty lines).

**Comment by cgcostume** [comment]
does not happen in ubuntu subsystem - still needs fix - windows is (still) main platform to provide support for.

**Comment by scheibel** [comment]
Can you re-check this? We changed the underlying source code generation and did a rewrite on all templates.
