### ISSUE TITLE
glpatch.xml issues

### ISSUE THREAD

**Issue by tsuoranta** [cginternals/khrbinding-generator#16]
What is the point of `<enum value="0x8B4B" name="GL_MAX_VARYING_COMPONENTS" alias="GL_MAX_VARYING_FLOATS"/>` - I see that not change anything compared to Khronos gl.xml

Same with `<group name="BufferAccessMask">`. I see _EXT version dropped, but this should not make a difference.

This is Khronos gl.xml: `<group name="BufferStorageMask">` - and glpatch.xml is missing some entries.

Same with `<group name="PathFontStyle">`.

What you do for `<command><proto>void <name>glListDrawCommandsStatesClientNV` is questionable: parameter `sizes` type `GLsizei` should be surrounded by `<ptype>` tag.

`<!-- patch probably wrongly named parameter groups -->` seems wrong. Reading path rendering extension spec, neither glGetPathMetricRangeNV() nor glGetPathMetricsNV() accepts BOLD_BIT or ITALIC_BIT, and reading Khronos gl.xml PathRenderingMaskNV = PathMetricMask + GL_BOLD_BIT_NV + GL_ITALIC_BIT_NV.

**Comment by scheibel** [comment]
Thanks for reporting. Most of the entries in the patch.xml were added before 2015. Probably they are obsolete and mostly misleading by now and need a rewrite.

**Comment by scheibel** [comment]
We did a rewrite of the parsing code. Now, the patch XML file is not used anymore.
Instead, we use parser-integrated Python functions to adapt the contents to our needs.
All of your mentioned cases are not part of the patching anymore.
